

name: ARMTemplateDeployment

on:
  workflow_dispatch:

jobs:
  armDeploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure login
        uses: Azure/Actions/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
