

name: ARMTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy ResourceGroup rg-GithubActions with Az Cli
        uses: Azure/cli@v1
        with:
          inlinescript: |
            az deployment sub create --location "UK West" --template-file ./arm-templates/resourcegroup.json

