name: List RGs

on:
  workflow_dispatch:

jobs:
  rgDeploy: 
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          

      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
